# Generated by Django 4.0 on 2023-03-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=5)),
                ('room_status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('dirty', 'Dirty'), ('cleaned', 'Cleaned'), ('outofservice', 'Out of Service')], max_length=20)),
                ('room_type', models.CharField(choices=[('ac', 'AC'), ('nonac', 'NonAC')], max_length=20)),
                ('beds', models.PositiveIntegerField()),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='room_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
