# Generated by Django 4.0 on 2023-03-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_rename_room_id_booking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
